### ISSUE TITLE
Get Snowflake biuld via gomobile bind

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/AndroidPluggableTransports#9]
Another one:
https://github.com/keroserene/snowflake

**Comment by uumaro** [comment]
Use https://git.torproject.org/pluggable-transports/snowflake.git rather than https://github.com/keroserene/snowflake please; the latter is now only a mirror.

**Comment by n8fr8** [comment]
This is now where dev is happening... including pure go: https://github.com/cohosh/snowflake

**Comment by eighthave** [comment]
I was able to build an AAR from an old commit keroserene/snowflake@3bcd60ad106a6258048179c797089da79ab28214, donno if it is useful.  The AAR is available here https://gitlab.com/eighthave/snowflake/-/jobs/622167415/artifacts/download

I'll try bisecting the project to find where it stopped building with _gomobile_.

**Comment by eighthave** [comment]
Figured it out: the build process was set up pre Go v1.11, which added the _go.mod_ functionality.  Adding _go.mod_ to snowflake (keroserene/snowflake@920f6791f3ec8e7467c43ee0cefffe63200bed2b) broke the _gomobile_ build.  Setting `GO111MODULE=off` fixes the build:
https://dev.to/maelvls/why-is-go111module-everywhere-and-everything-about-go-modules-24k

The build log and artifacts are here:
https://gitlab.com/eighthave/snowflake/-/jobs/625228544

**Comment by uumaro** [comment]
In my opinion, you should use a more recent commit of snowflake. Anything [7043a055f](https://gitweb.torproject.org/pluggable-transports/snowflake.git/log/?id=7043a055f9fb0680281ecffd7d458a43f2ce65b5) or later will do. Not only does it remove the [go-webrtc](https://github.com/keroserene/go-webrtc) dependency which is no longer maintained, it has the [Turbo Tunnel](https://lists.torproject.org/pipermail/anti-censorship-team/2020-February/000059.html) features that are encessary for a reasonable user experience. These are the features that enable a client to switch to a new temporary proxy when their old proxy goes away. (And, importantly, to get a working connection at all when the first polled proxy doesn't work, which for some types of NAT happens [around 70% of the time](https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/issues/33666#note_2595313).)

Tor Browser [uses `GO111MODULE=off`](https://gitweb.torproject.org/builders/tor-browser-build.git/tree/projects/go/config?h=tbb-10.0a1-build1#n22) so that's reasonable. It also [sets `CGO_ENABLED=1`](https://gitweb.torproject.org/builders/tor-browser-build.git/tree/projects/snowflake/build?h=tbb-10.0a1-build1#n8) for Android only; I'm not sure why, but a comment says the build breaks otherwise. [853e75e9](https://gitweb.torproject.org/builders/tor-browser-build.git/commit/?h=tbb-10.0a1-build1&id=853e75e9276432a39153db2e3fa54375af9b8822) is the commit from [#28672](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/28672#note_2657406) that added Snowflake to Tor Browser 10.0a1.

**Comment by uumaro** [comment]
> In my opinion, you should use a more recent commit of snowflake. Anything [7043a055f](https://gitweb.torproject.org/pluggable-transports/snowflake.git/log/?id=7043a055f9fb0680281ecffd7d458a43f2ce65b5) or later will do.

My bad; I just noticed from [the build output](https://gitlab.com/eighthave/snowflake/-/jobs/625228544#L16) that you are actually using a sufficiently new version of Snowflake. Never mind. I was confused by the [earlier comment](https://github.com/guardianproject/AndroidPluggableTransports/issues/9#issuecomment-653252276) referring to https://github.com/keroserene/snowflake/commit/3bcd60ad106a6258048179c797089da79ab28214.

**Comment by eighthave** [comment]
Seems that this build process I just got working does not need `CGO_ENABLED=`, I never messed with it either way.

I'd like to submit my _.gitlab-ci.yml_ in a merge request?  Which git project is the place to do that these days?

**Comment by uumaro** [comment]
> I'd like to submit my _.gitlab-ci.yml_ in a merge request? Which git project is the place to do that these days?

https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake

**Comment by eighthave** [comment]
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/merge_requests/4 has the build working without either `CGO_ENABLED=1` or `GO111MODULE=off`

**Comment by eighthave** [comment]
@n8fr8 @tladesignz is this still relevant, given the new lib?  I think its safe to close.

**Comment by n8fr8** [comment]
Agreed, thanks. For anyone looking for Snowflake and our latest effort at a mobile friendly PT library, please check out: https://github.com/tladesignz/IPtProxy

**Comment by eighthave** [comment]
is it ready to have an official home in https://github.com/guardianproject?

**Comment by tladesignz** [comment]
Happy to move it, when you allow it!

**Comment by eighthave** [comment]
add me as an admin to your project, and I'll move it.
